name: Backend Validation

on:
  pull_request:
    paths:
      - 'auto-analyst-backend/**'

jobs:
  validate-backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        working-directory: ./auto-analyst-backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Validate app.py
        working-directory: ./auto-analyst-backend
        run: |
          # Run app.py in validation mode (add a flag if needed)
          # If app.py can be run without arguments, use:
          python -c "import app; print('App validation successful')"
          # If specific validation is needed, uncomment and modify:
          # python app.py --validate 