
name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Git user identity
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Push to Hugging Face hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd auto-analyst-backend
          git remote remove origin || true
          git remote add origin https://Ashad001:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Ashad001/auto-analyst-backend
          git add .
          git commit -m "Sync backend to Hugging Face hub" || true
          git push --force origin main