name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Git user identity
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Install Git LFS
        run: |
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
          sudo apt-get install git-lfs
          git lfs install

      - name: Clean up repository and remove unwanted files
        run: |
          git rm --cached -r .
          git add .
          git commit -m "Clean up repository"

      - name: Apply .gitignore and ensure node_modules are not tracked
        run: |
          echo "node_modules/" >> .gitignore
          git add .gitignore
          git commit -m "Update .gitignore to exclude node_modules"

      - name: Track binary files with Git LFS (only in backend)
        run: |
          cd auto-analyst-backend
          git lfs track "*.exe"
          git lfs track "*.node"
          git add .gitattributes
          git commit -m "Track binary files with Git LFS"

      - name: Push to Hugging Face hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd auto-analyst-backend
          git remote remove origin || true
          git remote add origin https://Ashad001:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Ashad001/auto-analyst-backend
          git add .
          git commit -m "Sync backend to Hugging Face hub" || true
          git push --force origin main
